version: "3.8"

services:
  runner:
    image: sscspccloudnuage/github-runner:latest
    restart: always
    environment:
      RUNNER_NAME: ${RUNNER_NAME}
      RUNNER_REPO_URL: ${RUNNER_REPO_URL}
      GITHUB_TOKEN: ${GITHUB_TOKEN}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock      
      - config:/home/runner
      # - /home/bernard/_work:/home/runner/_work

volumes:
  config: