name: build

on:
  push:
    branches:
      - main
  release:
    types:
      - published


env:
  IMAGE_NAME: ssccloudspcnuage/github-runner
  IMAGE_TAG: ${{ github.event_name != 'release' && github.sha || github.event.release.tag_name }}

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event_name == 'release' || contains(toJson(github.event.commits), '[skip ci]') == false
    steps:

      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          context: ./docker 
          file: ./docker/Dockerfile          
          tags: ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }},${{ env.IMAGE_NAME }}:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

      - name: Scan for vulnerabilities
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}'
          format: table
          exit-code: 1
          ignore-unfixed: true
          severity: CRITICAL        